### ISSUE TITLE
AsyncRead interoperability with `async_std` is not compiling

### ISSUE THREAD

**Issue by jrop** [http-rs/surf#139]
I'm sorry if this a n00b question, but I am attempting to use this library with async_std, in the following manner:

```rust
  let resp = surf::get(the_url).await?;
  let mut dest_tmp_file = async_std::fs::File::create("TODO").await?;
  async_std::io::copy(&mut resp, &mut dest_tmp_file).await?;
```

The compiler, of course, does not like this:

```
19 |   async_std::io::copy(&mut resp, &mut dest_tmp_file);
   |   ^^^^^^^^^^^^^^^^^^^ the trait `futures_io::if_std::AsyncRead` is not implemented for `surf::response::Response`
```

I was just wondering if there is a way handle this elegantly.  Thanks for the awesome crate, BTW!

**Comment by goto-bus-stop** [comment]
This is probably because the current version of Surf that is published to crates.io uses a prerelease version of the `futures` crate, while async-std uses a stable version. So there are two versions of the futures crate providing two different AsyncRead traits (even if the actual trait definition is identical).

This is addressed in surf@2, which uses the stable `futures` crate, but that's not yet released. In the mean time, you can depend on Surf from the github repo:

```toml
surf = { git = "https://github.com/http-rs/surf" }
```
and that should interact well with async-std.

**Comment by jrop** [comment]
Wow, fast reply!  Thanks.  I'll give that a shot

**Comment by jrop** [comment]
That did the trick.  Thanks a bundle for the quick and helpful response.
