### ISSUE TITLE
Possible to release a 1.0.4

### ISSUE THREAD

**Issue by jonathandturner** [http-rs/surf#142]
The latest version of 'surf' in crates.io is 1.0.3 and still uses the futures-preview crate. I noticed the version in master had moved to the standard futures crate. Would it be possible to release a 1.0.4 that includes this update, by chance? We've been moving off of futures-preview and this is the last step. We're happy to help test if that's helpful. 

Looking forward to surf 2.0!

**Comment by jaroslavpachola** [comment]
There is more. The current master version is able to correctly read response bodies in other encodings (namely ISO8859-1 returned to my sample application yesterday when trying to the Google homepage) and release 1.03 fails to do it with UTF-8 decode error. A new release would be great!

**Comment by goto-bus-stop** [comment]
It's a breaking change because of the futures update, unfortunately. I would also like it if we could get a 2.0 out with what we have now though, _especially_ for the futures update…or maybe a 2.0.0-alpha.0 if we want to get the remaining items from #107 in for marketing reasons :smile: 
@yoshuawuyts what do you think about that?

**Comment by yoshuawuyts** [comment]
@goto-bus-stop you summarized it perfectly; we're working towards that as part of #146.

**Comment by goto-bus-stop** [comment]
Released 2.0.0-alpha.0: https://github.com/http-rs/surf/releases/tag/v2.0.0-alpha.0 Thanks!
