### ISSUE TITLE
surf::Response does not implement Index yet

### ISSUE THREAD

**Issue by jbr** [http-rs/surf#184]

**Comment by jsha** [comment]
I think this is describing the use of Index for looking up headers in the response, e.g. `response["Content-Length"]`. Is that right?

I think it might be preferable not to implement Index, since it encourages users to risk a panic based on untrusted data. For instance, if I write an HTTP client that tries to examine `response["Content-Length"]`, all the server has to do to crash my client is send a response without that header field.

The safe way to use Index here would be for the user to check if the header exists first:

```
if let Some(values) = response.header('Content-Length') {
  response['Content-Length']
}
```

But by then it's just as easy to use `values`.

**Comment by jbr** [comment]
It is important for surf Response and Request to have a similar interface to tide and the underlying http-types for the principle of least surprise. Currently, Index is an exception to this, which is what this issue represents

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/commit/c22693e2e0a42e0d975fbc3c508b86c677256779 fixed this.
