### ISSUE TITLE
Please support http-client's new h1_client_rustls feature

### ISSUE THREAD

**Issue by joshtriplett** [http-rs/surf#272]
I'd like to use surf with http-client's new `h1_client_rustls` feature, so I can avoid openssl. Please consider plumbing that option through as a surf backend feature.

**Comment by djarb** [comment]
Seconded, thank you.

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/pull/271 exists but I am not really sure what the best way to design these feature flags is. Would `"h1-rustls-client"` be suitable?

**Comment by djarb** [comment]
That would satisfy my needs

**Comment by Fishrock123** [comment]
Further discussion exists in https://github.com/http-rs/surf/pull/271#issuecomment-762535474

I also need this for https://github.com/nlopes/libhoney-rust/pull/61

The question is how can the feature flags be structured in a "nice" way. I am not super happy with the http-client `h1_client_rustls` flag, which is why I had not yet released it. But also, I am not sure if there is presently an alternative since we essentially have a matrix of client+tls feature functionality, and [weak dependency features](https://github.com/rust-lang/cargo/issues/8832) have not yet stabilized.

**Comment by joshtriplett** [comment]
This seems to be working in the released surf, at this point. While the structure of the feature flags could potentially change in the future, I think this issue as reported has been addressed.

Thank you!
