### ISSUE TITLE
Please support Native - TLS and Rust-TLS conditional compilation

### ISSUE THREAD

**Issue by zhuxiujia** [http-rs/surf#283]
Please support ```native-tls``` and ```rust-tls``` conditional compilation

* This is because ```native-tls``` requires the operating system to install Open-SSL.（The Open-SSL version has serious problems on some cloud service operating systems, Upgrading Open-SSL is not supported）
* But  the  ```rust-tls```  No system  dependence whatsoever
* As far as I know, ``` reqwest``` currently supports conditional compilation switching

**Comment by Fishrock123** [comment]
There is a PR for this, I just need to actually get to it: https://github.com/http-rs/surf/pull/271

It will only be supported for the `h1-client`.

We don't use `reqwest` for the `hyper-client`. It will not support `rustls` because it uses `hyper` directly with tls support from [`hyper-tls`](https://crates.io/crates/hyper-tls) which only uses native-tls. If you would like rustls support with hyper please open an issue at https://github.com/hyperium/hyper-tls/issues

**Comment by Fishrock123** [comment]
The `h1-client-rustls` support has been merged: https://github.com/http-rs/surf/pull/292
