### ISSUE TITLE
What's the type of `surf::Client::new()` ?

### ISSUE THREAD

**Issue by fukuang** [http-rs/surf#54]
Hello, I'm trying to create a client instance and pass it to functions for reuse:
```
let client = surf::Client::new();
get_item(client, url);
```

But what type should I use for the function parameter ?
```
async fn get_item(client: ???, url: String) -> ...
```

**Comment by yoshuawuyts** [comment]
@fukuang ahhh, yes this is a great question! We're not exposing the concrete client types yet (because of API stability guarantees) so I see where you're coming from. I'm not sure if there's quite an escape hatch yet with `surf::middleware::HttpClient`, but otherwise using the `one_off` methods might still be your best bet for now.

We should provide a better fix for this though; marking this as a bug for now!

**Comment by vorot93** [comment]
`one_off` methods spawn a thread per call which is not really a sensible approach.

**Comment by IslandUsurper** [comment]
It appears you can use `fn foo<C: HttpClient>(client: Client<C>)`, but I'm writing a SDK for a REST API, and I'd rather not change every function in my library to be generic over the one type.

Would it possible to make the structs public, but not their implementations? Until they are stabilized, anyway. `HyperClient::new()` is only crate-public, and the only client that is Default is IsahcClient. If it doesn't need to be, then all of these structs can be referenced without being instantiated. I'll see if I can make a PR for this.

**Comment by rbtcollins** [comment]
In 1.0.3 you can't even embed the surf client in a struct:

```
struct Client<C: surf::http_client::HttpClient>...
```

because of this privateness issue - perhaps thats changed in 2.x? Anyhow - with 2 in alpha and no ability to embed the client, its pretty hard to use, stability aside.

The desire to embed this is because there appears to be no way to configure the client to automatically add headers to requests, so I need to wrap the client in a thing that can be called in a few different ways, which will add the relevant headers to the get/put etc requests before forwarding handing off the request.

**Comment by stevepryde** [comment]
@rbtcollins I've run into exactly the same issue. Just trying to add surf support into `thirtyfour` (selenium client). This is a pretty big deal-breaker.

**Comment by bbigras** [comment]
Any progress on this?

**Comment by goto-bus-stop** [comment]
Since #193, you can use `surf::Client` as a concrete type :)
