### ISSUE TITLE
Allow passing custom TLS keys/certs to `Client`

### ISSUE THREAD

**Issue by kamyuentse** [http-rs/surf#56]

**Comment by kamyuentse** [comment]
@yoshuawuyts Sorry for the vague. I am looking a way to specify the client certificate when interactive with the server that enables two-way TLS. A case in point is the `--cert | --cacert` options of `curl`.

**Comment by yoshuawuyts** [comment]
@kamyuentse thanks for the issue! -- I agree this is something we should support. I did a quick survey and a small API proposal at the end:

# Survey
## Nodejs
- https://nodejs.org/api/https.html#https_https_request_url_options_callback
```js
const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};
options.agent = new https.Agent(options);

const req = https.request(options, (res) => {
  // ...
});
```

## node-fetch

Pass it a custom `http.agent` that has the tls options.
- https://github.com/bitinn/node-fetch#options

## Reqwest
- https://docs.rs/reqwest/0.9.20/reqwest/struct.ClientBuilder.html#method.add_root_certificate

```rust
// read a local binary DER encoded certificate
let mut buf = Vec::new();
File::open("my-cert.der")?.read_to_end(&mut buf)?;

// create a certificate
let cert = reqwest::Certificate::from_der(&buf)?;

// get a client builder
let client = reqwest::Client::builder()
    .add_root_certificate(cert)
    .build()?;
```

# Proposal

Probably the right way to go about it is to provide an API as:
```rust
let mut client = surf::Client::new()
    .insert_cert(File::open("test/fixtures/keys/agent2-key.pem")?)?;

let req1 = client.get("https://httpbin.org/get").recv_string();
```

where

```rust
impl Client {
    fn insert_cert(mut self, cert: impl Read) -> Result<Self, surf::Exception>;
}
```
Possibly we should also be able to pass keys here.

One thing to be on the lookout for though is that we can pass the cert buffers to both `curl` and `hyper`. We should disable these methods in `fetch/wasm`.

**Comment by johnpmayer** [comment]
for custom CA, an alternative solution would be to by-default use something like rustls_native_certs::load_native_certs; the user would just configure their OS root store with the custom certificate(s) that they wanted to trust

**Comment by mendelt** [comment]
@johnpmayer This issue is a bit vague but as @kamyuentse clarified is about client certificates. The OS root store us used to store server certificates that are trusted by the host.

@yoshuawuyts I like how your proposal does not force you to read certificates from the file-system by accepting `impl Read` (instead of a `PathfBuf` like isahc) You will need a mechanism to specify a client certificate as well as the private key in order to use it to authenticate though. There are a couple of file formats. PEM and DER are encodings/file formats that only store a certificate. So they need to be accompanied by a separate key file. P12 is a file format that encodes a certificate as well as the accompanying private key. P12 files are commonly encrypted so you'd need a decryption passphrase too.

In the future we might also support a signing callback instead of a private key. This is commonly used in scenario's where the private key is stored on a smartcard or hardware security module for example where the key itself is not available but the HSM can be used to perform cryptographic operations with the key.

**Comment by Fishrock123** [comment]
This is now possible with the async-h1 client (`"h1-client"` feature), but you'll need to add `http-client` `6.4`+ as a dependency directly and enable it's `"unstable-config"` feature (and probably also set `default-features = false`).

See https://docs.rs/http-client/6.4.1/http_client/struct.Config.html - different config exists if you are using the `native_tls` or `rustls` backend.

This can be then used by surf by:
```rust
let inner_client: http_client::H1Client = config.try_into().unwrap(); // Infalliable.
let client = surf::Client::with_http_client(inner_client);
```
See https://docs.rs/surf/2.2.0/surf/struct.Client.html#method.with_http_client

----

This style of configuration will make its way into Surf itself sometime Soon(tm) _(eventually)_, and will be much nicer to use.

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/releases/tag/v2.3.0 has brought Config support to Surf, with the same above caveats that tls config is only supported for the async-h1 client
