### ISSUE TITLE
How to get the request body

### ISSUE THREAD

**Issue by CarlosLanderas** [http-rs/surf#67]
Hello guys. I am checking source code inside surf::Request and I am trying to find a way to inspect body bytes / body string without moving ownership because I need to send some signed headers with the content, and the use the same request to be sent using http client.

The method I'm trying to do would be something like this:

```rust

 pub(crate) async fn sign(request: &surf::Request<impl HttpClient>) {

        let host = request.url();
        let verb = request.method()
                        .to_string()
                        .to_uppercase();

      //Need to read request without moving

   }
```
Im seeing there is a bunch of methods to set the body but I can't find anyone to read the bytes that are already inside the body. Any way to do this?

Thanks!

**Comment by k-nasa** [comment]
surely. I will try to add.

**Comment by yoshuawuyts** [comment]
@CarlosLanderas hi, thanks for filing this! -- I think the answer is that there's not really a good way to go about this. Because when reading a request body, we *have* to assume it's being consumed. E.g. if we have a stream from a socket, or a circular buffer, after reading the data it can be lost again.

So instead what I'd recommend is to invert the logic. Sign the file inside `surf` middleware, as data goes through. If that's not possible yet, then we should put in some effort to support that use case.

Also apologies for the late reply; I've had a lot on my plate recently. Thanks heaps for your patience!

**Comment by CarlosLanderas** [comment]
Thanks @yoshuawuyts

I acomplished this, I don't remember how because it was some time ago. :P

https://github.com/CarlosLanderas/azure-app-configuration/blob/master/src/client.rs
https://github.com/CarlosLanderas/azure-app-configuration/blob/master/src/request_sign.rs
