### ISSUE TITLE
Making the `Client` to use dynamic dispatch

### ISSUE THREAD

**Issue by pimeys** [http-rs/surf#69]
Instead of passing the internal implementation in `Client<T: HttpClient>`, why not just hiding it by using dynamic dispatch and a smart pointer? In the end, the performance hit would not be that bad compared to the time taken by the network traffic itself.

So, instead of

```rust
#[derive(Debug, Default)]
pub struct Client<C: HttpClient> {
    client: C,
}
```

we'd have

```rust
#[derive(Debug, Default)]
pub struct Client {
    client: Box<dyn HttpClient>,
}
```

Would be nice in some of our cases, where we need to keep the `Client` in a struct, and we might need to switch the underlying implementation e.g. in cases where we build for wasm. Having dynamic dispatch wouldn't change all the type signatures.

**Comment by yoshuawuyts** [comment]
@pimeys this would be fantastic, even though it's a breaking change. I'm actually quite open for this, and it might actually be the kind of thing that if we do it sooner rather than later folks will have an overall better experience.

**Comment by pimeys** [comment]
What might be a problem is the associated `Error` type in the `Client`. It's not that nice anymore when boxing.

What we could do:
- `Box<dyn Error + Send + Sync + 'static>`
- Have our own error type and `From` the external errors into the internal type.

What I think is useful is to be able to see actual errors when utilizing the client. Many clients using a http client internally need to map from different http error types, making the boxed error clunkier to use.

**Comment by IslandUsurper** [comment]
The library I'm writing that would use surf is also in the middle of changing error libraries, so maybe I ought to try doing it this way too. I'll tinker a bit and see what shakes out.

**Comment by tomhoule** [comment]
I'm seriously thinking about basing the http part of [graphql-client](https://github.com/graphql-rust/graphql-client) on surf. Since `graphql-client::Client` would wrap around `surf::Client`, we need the type parameter to be hidden to avoid leaking the `surf::middleware::HttpClient` bound in the public API.

discussion issue: https://github.com/graphql-rust/graphql-client/issues/272

**Comment by IslandUsurper** [comment]
I've attempted to make this change, and I got as far as making Client, Request, and Middleware, and Next use dynamic dispatch, and then started running into the problems @pimeys mentioned about the associated Error type. I tried to declare the client type as `Box<dyn HttpClient<Error=dyn std::error::Error>>`, but that ends up making `HttpClient::send` object-unsafe (`Self::Error` in the return value).

> Have our own error type and From the external errors into the internal type.
I think this will be the way to go, but I haven't yet looked into the implementations to see how similar the various error types are. But it does mean that anyone wanting to implement `HttpClient` will have to implement `Into<SurfError>` for their error type, instead of `From`. Not ideal, but that is why this escape hatch exists.

**Comment by IslandUsurper** [comment]
I think I'm stuck now. I've got a [some code](https://github.com/IslandUsurper/surf/tree/dyn-http-client) that almost has it done, but the compiler still thinks `HttpClient` can't be a trait object, because it is `Sized`. I think it's because `HttpClient: Clone`, which implies `Sized`.

Also, I did not create a wrapping Error type very well. It was a naïve implementation, but I didn't want to spend a whole lot of time on that part. But I think it's necessary for `HttpClient` to be `Clone`, so I don't think we're going to be able to do things this way.

**Comment by icewind1991** [comment]
From what I can tell you can't have trait objects with multiple trait bounds (`HttpClient + Clone`)

I've expanded on the WIP by @IslandUsurper removing the extra trait bounds and using an `Arc` instead of `Box` to allow cloning the client

https://github.com/icewind1991/surf/tree/dyn-http-client

**Comment by yoshuawuyts** [comment]
This def seems like the right solution for us. All we need is a patch to fix that. Don't believe one exists yet; would someone be willing to submit one? Thanks!

This will be part of a 2.0 release.

**Comment by jonathandturner** [comment]
I gave this a try, and hit:

```
the trait `http_client::HttpClient` cannot be made into an object
the trait cannot require that `Self : Sized`
```

Sounds like we may need to make HttpClient object safe first?

**Comment by yoshuawuyts** [comment]
@jonathandturner good point; filed https://github.com/http-rs/http-client/pull/18 to resolve it.

**Comment by goto-bus-stop** [comment]
Is the associated `Error` type in HttpClient also a problem for object safety?

**Comment by yoshuawuyts** [comment]
@goto-bus-stop I'm actually unsure; I thought it was limited to `self` types, so would assume not? But don't have a definitive answer. Maybe let's try and see?

**Comment by goto-bus-stop** [comment]
Spent some more time on this but it's tricky :upside_down_face: 

```rust
Box<dyn HttpClient<Error = http_client::Error>>
```
…still doesn't quite do the trick. It needs a bunch of other trait bounds as well. Maybe the most plausible approach would be to add an internal trait like this
```
trait InnerSurfClient: HttpClient<Error = http_client::Error> + Clone + Send + etc {
}
```
and add a blanket impl for that, and refer to it as `Box<dyn InnerSurfClient>`

**Comment by yoshuawuyts** [comment]
@goto-bus-stop perhaps we could hard code `http_client` to always return an `http_types::Error`, removing the generic bound altogether?

**Comment by skade** [comment]
@goto-bus-stop the main problem is that "Clone" is not object-safe.

**Comment by goto-bus-stop** [comment]
@skade Ahhhhhh I see, now the errors about Clone make sense…

**Comment by SirWindfield** [comment]
Is there something special that needs to be resolved before this can actually be tackled down? @icewind1991 did a great job on his branch using `dyn`.

I am currently using `surf` in a project and the type parameters do prevent me from going any further right now.

**Comment by Fishrock123** [comment]
This is the correct http-client patch to make `HttpClient` usable as a trait object: https://github.com/http-rs/http-client/pull/30

However, https://github.com/http-rs/http-client/pull/29 is also more-or less required, or at least the type bounds without it would be very convoluted.

**Comment by Fishrock123** [comment]
Done in https://github.com/http-rs/surf/pull/193
