### ISSUE TITLE
make NativeClient public

### ISSUE THREAD

**Issue by frostRed** [http-rs/surf#96]
I have a problem when I want to wrap my client.

The Problem like this: https://stackoverflow.com/questions/45253784/expected-type-parameter-found-struct.

And my code:

```
use surf::{middleware::HttpClient, Client};

pub struct NodeRpcClient2<C: HttpClient> {
    client: Client<C>,
    upstream_url: String,
}

impl<C: HttpClient> NodeRpcClient2<C> {
    pub fn new(url: String) -> Self {
        let client = Client::new();
        NodeRpcClient2 {
            client,
            upstream_url: url,
        }
    }
}

```

#69 seems to work.

**Comment by yoshuawuyts** [comment]
@frostRed good point; yeah we should go through with that change. All we need now is a patch for it, and then we can use that to cut a 2.0 release. I think it's time.

**Comment by strohel** [comment]
I think this was resolved in #124 by moving NativeClient into separate crate http-client (where it is public).

**Comment by andrewbanchich** [comment]
I can't figure out how to import `NativeClient` with this. The surf's `2.0.0-alpha.4` docs now have `NativeClient` as a link in function signatures since it's public, but when I click it it just takes me to a [resource does not exist](https://docs.rs/surf/2.0.0-alpha.4/surf/struct.Client.html) page. I also can't find a way to import it from the `http_client` crate. When I try, I just get

```
could not find `native_client` in `http_client`
````

**Comment by andrewbanchich** [comment]
Maybe `surf` could re-export `NativeClient` so that we don't need to add another dependency directly just for this use case?

**Comment by goto-bus-stop** [comment]
#194 was just merged, with that you don't need the NativeClient at all anymore because `surf::Client` does not have a generic parameter :)
